on: ["push", "pull_request"]

name: Test

jobs:
    functional:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]   # eventually add `windows-latest`
                python-version: [3.9]

        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GETH_VERSION: 1.10.26

        steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
              python-version: ${{ matrix.python-version }}

        - name: Cache Geth
          id: cache-geth
          uses: actions/cache@v3
          with:
            path: $HOME/.local/bin
            key: ${{ runner.os }}-geth-$GETH_VERSION

        - name: Install Geth
          if: steps.cache-geth.outputs.cache-hit != 'true'
          run: |
            mkdir -p $HOME/.local/bin
            wget -O geth.tar.gz "https://github.com/ethereum/go-ethereum/archive/v$GETH_VERSION.tar.gz"
            tar -zxvf geth.tar.gz
            cd go-ethereum-$GETH_VERSION
            make geth
            cp ./build/bin/geth $HOME/.local/bin

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip uninstall eth-ape --yes
            pip install .[test]

        - name: Run Tests
          run: pytest -m "not fuzzing" -s --cov=src -n auto
