on: ["push", "pull_request"]

name: Test

jobs:
    functional:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]   # eventually add `windows-latest`
                python-version: [3.9]

        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
              python-version: ${{ matrix.python-version }}

        - name: Install Geth
          run: |
            GETH_VERSION=1.10.26
            DEST=$RUNNER_TOOL_CACHE/geth/

            echo $PATH
            exit 69

            # if [ ! -e geth-versions/geth-$GETH_VERSION/go-ethereum-$GETH_VERSION/build/bin/geth ] ; then
            mkdir -p $HOME/.ethash
            mkdir -p geth-versions/geth-$GETH_VERSION
            cd geth-versions/geth-$GETH_VERSION
            wget -O geth.tar.gz "https://github.com/ethereum/go-ethereum/archive/v$GETH_VERSION.tar.gz"
            tar -zxvf geth.tar.gz
            cd go-ethereum-$GETH_VERSION
            make geth

            cp ./build/bin/geth $RUNNER_TOOL_CACHE
            which geth
            geth makedag 0 $HOME/.ethash
            # fi

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip uninstall eth-ape --yes
            pip install .[test]

        - name: Run Tests
          run: pytest -m "not fuzzing" -s --cov=src -n auto
